### PR TITLE
Added package nim_telegram_bot

### PR DESCRIPTION
**Pull request by juancarlospaco**
Builds on top of Telebot, usable just editing `config.ini`, but can also use plugins just putting it on the `./plugins/` folders.

### CODE REVIEW

**Comment by dom96** [comment]
This is awesome :O

**Comment by dom96** [comment]
Sadly I can't install it:

```
» nimble install https://github.com/juancarlospaco/nim-telegram-bot
Downloading https://github.com/juancarlospaco/nim-telegram-bot using git
       Tip: 6 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_43367/githubcom_juancarlospaconimtelegrambot/nim_telegram_bot.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     private/tmp/nimble_43367/githubcom_juancarlospaconimtelegrambot/nim_telegram_bot.nimble(13, 27) Error: undeclared identifier: 'telebot'.
```

**Comment by juancarlospaco** [comment]
Fixed :+1: 

```bash
$ nimble install https://github.com/juancarlospaco/nim-telegram-bot

Downloading https://github.com/juancarlospaco/nim-telegram-bot using git
  Verifying dependencies for nim_telegram_bot@0.2.2
      Info: Dependency on openexchangerates@any version already satisfied
  Verifying dependencies for openexchangerates@0.1.0
      Info: Dependency on telebot@any version already satisfied
  Verifying dependencies for telebot@0.4.1
 Installing nim_telegram_bot@0.2.2
   Success: nim_telegram_bot installed successfully.

$
```

**Comment by dom96** [comment]
Works now, but shouldn't you specify a ``bin`` in your .nimble file so that it gets compiled?

**Comment by juancarlospaco** [comment]
Fixed :+1: 

```bash
$ nimble install https://github.com/juancarlospaco/nim-telegram-bot

Downloading https://github.com/juancarlospaco/nim-telegram-bot using git
  Verifying dependencies for nim_telegram_bot@0.2.3
      Info: Dependency on openexchangerates@any version already satisfied
  Verifying dependencies for openexchangerates@0.1.0
      Info: Dependency on telebot@any version already satisfied
  Verifying dependencies for telebot@0.4.1
 Installing nim_telegram_bot@0.2.3
   Building nim_telegram_bot/nim_telegram_bot using c backend
   Success: nim_telegram_bot installed successfully.

$
```

**Comment by juancarlospaco** [comment]
Thanks!,... :cat:

**Pull request merged**
