### PR TITLE
Add package vmvc

### PR DESCRIPTION
**Pull request by kobi2187**

### CODE REVIEW

**Comment by kobi2187** [comment]
hi, first time creating a package. 
if something breaks let me know, thanks!

**Comment by trustable-code** [comment]
"url" and "web" are missing / invalid urls.

**Comment by kobi2187** [comment]
> "url" and "web" are missing / invalid urls.
@trustable-code I'm sorry, what does that mean?

**Comment by kobi2187** [comment]
hi @trustable-code can you retry now? I think it's fixed

**Comment by ThomasTJdev** [comment]
Hi @kobi2187 

You package is missing the method. In the method, you need to insert git. It should look like this:
```
"method": "git",
```
_____

Github can help you in checking you PR. The screenshot 1 below shows that your PR has an error. If you click on the `Details` button, it will send you to a page, where you can see the error is `E: vmvc has an unknown method:` (screenshot 2).

### screenshot 1
git_v1

### screenshot 2
git_v2

**Comment by kobi2187** [comment]
Hi @ThomasTJdev 
Thanks for the help, I think it's alright now. 
btw, what are the other options for the "method" key? Can I use my hg repository instead?

**Comment by ThomasTJdev** [comment]
Hi @kobi2187 

This [repository](https://github.com/nim-lang/packages) has a description of what is needed. See the section "Adding your own package".

- method - The method that should be used to retrieve this package. Currently "git" and "hg" is supported.

**Pull request merged**
