### PR TITLE
Add mk

### PR DESCRIPTION
**Pull request by thisago**

### CODE REVIEW

**Comment by narimiran** [comment]
@dom96 @Araq what do we think of "impostor" group/project https://gitlab.com/nimlang ?

**Comment by Araq** [comment]
I think we should kindly ask @thisago to use a more descriptive project name.

**Comment by thisago** [comment]
Hi @narimiran, I selected this name because it was avaliable, if you want i can change to another one. sorry

**Comment by thisago** [comment]
yes, a agree, but the project is a handler to create folders and files on terminal, the name need to be short to write easier, I wrote the package name to "mk" because it is the name of command, the name as "mkfs" or "shmk" is better? sorry by my bad english. Thanks for the feedback

**Comment by thisago** [comment]
Thanks for the help, guys, I'm going to change the name of the gitlab group and the package name to "shmk" and make another pull request; I recommend that you get that group name from gitlab. Thank you for your help!

**Pull request closed without merging**
