### PR TITLE
Added package loopfusion

### PR DESCRIPTION
**Pull request by mratsim**

### CODE REVIEW

**Comment by dom96** [comment]
screen shot 2018-03-23 at 00 25 35

Pretty sure the structure is wrong too (your experiments folder should be skipped).

**Comment by mratsim** [comment]
I've updated the nimble file accordingly. Thanks!

**Comment by Yardanico** [comment]
@mratsim can you rebase this PR, so @dom96  will merge it?

**Comment by mratsim** [comment]
closing and reopening, I've deleted the branch

**Pull request closed without merging**
