### PR TITLE
Added nimzend package.

### PR DESCRIPTION
**Pull request by oderwat**
Native Nim Zend API glue for easy PHP extension development.

### CODE REVIEW

**Comment by oderwat** [comment]
Why don't you add that package @dom96 ?

**Comment by dom96** [comment]
Because resolving conflicts is a PITA and I keep forgetting :)

**Comment by dom96** [comment]
Sorry about the delay.

**Comment by oderwat** [comment]
I thought I did something wrong ... it's my first package. I am bleeding!

**Comment by dom96** [comment]
Oh, didn't realise it was your first. Sorry! Don't worry, you did nothing wrong. I just tend to put these things off when I can't just press the "Merge" button in PRs.

**Pull request merged**
