### PR TITLE
Add a simple bitarray library

### PR DESCRIPTION
**Pull request by YesDrX**

### CODE REVIEW

**Comment by ba0f3** [comment]
[binary](https://github.com/YesDrX/bitarray) should removed from the repo

**Comment by YesDrX** [comment]
> [binary](https://github.com/YesDrX/bitarray/blob/master/src/bitarray) should removed from the repo

removed

**Comment by YesDrX** [comment]
> [This file](https://github.com/YesDrX/bitarray/blob/master/src/utils.nim) will be installed into the global namespace, i.e. it will be importable via `import utils`. You need to put it into a folder named `bitarray`

done.

**Comment by narimiran** [comment]
Merged as a part of #1617.

**Comment by dom96** [comment]
The name of this package is wrong, I had to revert its addition: https://github.com/nim-lang/packages/commit/5416690d7331db79dd6686c35773d895da8b9864. You need to name it something else as `bitarray` is an existing package.

**Comment by ba0f3** [comment]
next time you should make a branch before do pull request

**Comment by YesDrX** [comment]
> next time you should make a branch before do pull request

sure.

**Comment by YesDrX** [comment]
nim-bitarray changed to nimbitarray.

**Pull request merged**
