### PR TITLE
Add package trot

### PR DESCRIPTION
**Pull request by ucpr**

### CODE REVIEW

**Comment by ucpr** [comment]
I've decided to archive the repository and close it

**Comment by Yardanico** [comment]
any specific reason for archiving the repo? :(

**Comment by ucpr** [comment]
The formatting of the external resources has changed significantly. We have decided to archive them as we don't have time to deal with them...

**Comment by ucpr** [comment]
On second thought, it doesn't seem so hard to deal with! I'll unarchive if I can fix it soon. thx :)

**Pull request closed without merging**
