### PR TITLE
Add package nimclipboard

### PR DESCRIPTION
**Pull request by genotrance**

### CODE REVIEW

**Comment by dom96** [comment]
```
~ » nimble install https://github.com/genotrance/nimclipboard                                                                          1 ↵
Downloading https://github.com/genotrance/nimclipboard using git
Setting up Git repo
Checking out artifacts
File doesn't exist: libclipboard.h
stack trace: (most recent call last)
private/tmp/nimble_13905/githubcom_genotrancenimclipboard/nimclipboard.nimble(24) installBefore
private/tmp/nimble_13905/githubcom_genotrancenimclipboard/nimclipboard.nimble(21) setupTask
Users/dom/projects/nim/lib/system/nimscript.nim(237) exec
Users/dom/projects/nim/lib/system/nimscript.nim(237, 7) Error: unhandled exception: FAILED: nimgen nimclipboard.cfg
```

**Comment by genotrance** [comment]
Looks like nimble is not updating nimgen to v0.3.0 which is the required version in nimclipboard.nimble. Can you try manually updating nimgen and check again?

**Comment by dom96** [comment]
That's annoying :/

**Comment by dom96** [comment]
``before install`` hooks need the ability to install dependencies. Actually you could run ``nimble install --deps-only`` in your hook, that should fix it, no?

**Comment by genotrance** [comment]
This goes back to our open PR:

https://github.com/nim-lang/nimble/pull/464

**Pull request merged**
