### PR TITLE
Update packages.json

### PR DESCRIPTION
**Pull request by Bennyelg**
change package name,

### CODE REVIEW

**Comment by dom96** [comment]
You should keep the old name IMO.

**Comment by Bennyelg** [comment]
I saw an example of how to add an alias in-order to let users to download the packages using the alias name and just did the follow,

here is an example from inside the package.json
```
  {
    "name": "monad",
    "alias": "maybe"
  },
  {
    "name": "maybe",
    "url": "https://github.com/superfunc/maybe",
    "method": "git",
    "tags": [
      "library",
      "functional",
      "optional",
      "monad"
    ],
    "description": "basic monadic maybe type for Nim",
    "license": "BSD3",
    "web": "https://github.com/superfunc/maybe"
  },
```

**Comment by dom96** [comment]
Why do you want to rename it? I think the current name is fine.

**Comment by Bennyelg** [comment]
@dom96 Because I want everyone install it `nimble install db_presto`
and use it `import db_presto`

**Comment by dom96** [comment]
Okay, but why do you want this name and not "presto", what's wrong with ``import presto``?

**Comment by Bennyelg** [comment]
because I wanted to save the conversion of importing databases in nim.
db_mysql
db_postgres
db_...

**Comment by dom96** [comment]
Alright, for this case you can just rename the package directly (there is no need to alias since your package is very new). I'll do it for you.

**Pull request closed without merging**
