### PR TITLE
Add package nery

### PR DESCRIPTION
**Pull request by David-Kunz**

### CODE REVIEW

**Comment by narimiran** [comment]
> This is work in progress, do not use.

Should we then make it part of the official packages, or not?

**Comment by David-Kunz** [comment]
Hi @narimiran,

I only created the package to reserve the name as I'm doing a YouTube series on its development: https://youtu.be/97egpJPhPWs

I'm not sure how to proceed, I wouldn't recommend making this part of the official packages.

Thanks and best regards,
David

**Comment by xflywind** [comment]
Hi @David-Kunz 
I think you can remove "do not use", then this PR can be merged.

**Comment by David-Kunz** [comment]
Hi @xflywind,

Thanks for the hint, I changed the readme.

Isn't it lowercase already? I thought I had changed that everywhere.

Best regards,
David

**Comment by xflywind** [comment]
Yeah, maybe these names can be renamed too

image

**Pull request merged**
