### PR TITLE
Add package semver

### PR DESCRIPTION
**Pull request by euantorano**

### CODE REVIEW

**Comment by dom96** [comment]
Added 1,409 and removed 1,396? Why so many changes?

**Comment by yglukhov** [comment]
linefeeds?

**Comment by euantorano** [comment]
I used `nimble publish`, it obviously decided to use linefeeds on my system. I'll close this PR and open a new one, sorry about that!

**Comment by dom96** [comment]
oh. That's a bug, think you could report that on Nimble's repo?

**Comment by euantorano** [comment]
Sure, I'll open an issue.

**Pull request closed without merging**
