### PR TITLE
nimrat added

### PR DESCRIPTION
**Pull request by apense**
it's a rational arithmetic module

### CODE REVIEW

**Comment by dom96** [comment]
I don't think https://github.com/apense/nimrat/blob/master/nimrat.nimble#L8 is required in your .nimble file.

**Comment by apense** [comment]
Agreed. Just removed it.

**Comment by apense** [comment]
But, you should reject this, I think. I just noticed that a rationals library was added to the standard lib.

**Comment by dom96** [comment]
Not necessarily. But it's your choice.

**Comment by apense** [comment]
I reopened it. Sorry for the indecision. This will hopefully be useful until the better module is added. But at least I can use this to write a number theory module for now.

**Comment by dom96** [comment]
I don't mind libraries which serve the same purpose as ones already in the standard library being added to this packages repo. Same goes for libraries which are already in this repo.

**Pull request merged**
