### PR TITLE
Add package nmiline

### PR DESCRIPTION
**Pull request by mzteruru52**
(This package needs NiGui to use)

### CODE REVIEW

**Comment by dom96** [comment]
The current tagged version on your package doesn't have a .nimble file so the installation fails. Please tag a new version (make sure you update the .nimble file with the correct version prior to tagging).

**Comment by mzteruru52** [comment]
Thank you , and I just added .nimble file on new release.

**Comment by mzteruru52** [comment]
Fixed.

**Comment by mzteruru52** [comment]
I fixed (‥ )
image
Would this be okay?

**Comment by dom96** [comment]
Sure, that seems fine. Strange that ``srcDir = "src"`` isn't enough though.

**Comment by mzteruru52** [comment]
This project  needs NiGui (other library) to use. Should I make some changes?

**Comment by ba0f3** [comment]
just add it to requires list in your nimble file, and dont make a new release for new version :)

**Comment by mzteruru52** [comment]
OK .　I would like to refer to you .
Thank you!

**Pull request merged**
