### PR TITLE
removed dash from the libtcod package name

### PR DESCRIPTION
**Pull request by Vladar4**

### CODE REVIEW

**Comment by dom96** [comment]
I think you should just rename it to libtcod.

**Comment by Vladar4** [comment]
Might be mistaken for the original library then, no? http://roguecentral.org/doryen/libtcod/

**Comment by dom96** [comment]
Up to you, the alternative is to rename https://github.com/Vladar4/libtcod_nim/tree/master/libtcod to ``libtcod_nim``.

**Comment by Vladar4** [comment]
Might moving https://github.com/Vladar4/libtcod_nim/tree/master/libtcod one level up be the option?
I.e.:
```
libtcod_nim/
    private/
    libtcod.nim
    README.md
    ...
```

**Comment by dom96** [comment]
yes, but ``private`` needs to be inside a ``libtcod_nim`` directory.

**Comment by Vladar4** [comment]
Done.

**Pull request merged**
