### PR TITLE
Added package translation

### PR DESCRIPTION
**Pull request by juancarlospaco**

### CODE REVIEW

**Comment by dom96** [comment]
So which is it? ``tinyslation`` or ``translation``?

**Comment by juancarlospaco** [comment]
The exported proc is `tinyslation`, the package `translation`. :smile_cat:

**Comment by dom96** [comment]
A bit inconsistent, but oh well.

**Comment by juancarlospaco** [comment]
Ok, next time I will use `tinyslation.tinyslation` like. :smiley_cat:

**Comment by dom96** [comment]
IMO ``tinyslation.translate`` would make most sense :)

**Pull request merged**
