### PR TITLE
Add intel hex library

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**

### CODE REVIEW

**Comment by dom96** [comment]
yay for more people deleting their repos and breaking CI :(

**Comment by Jeff-Ciesielski** [comment]
Yeesh :/.  Does this just require manual pruning?

**Comment by dom96** [comment]
yeah, but it's a pain since I've changed the repo settings to only allow pulls when tests pass :/

**Comment by Jeff-Ciesielski** [comment]
Yisssss.
image

Needed this to move forward with development.  I'll update the "Companies that use Nim" page once we ship our new code :D

**Pull request merged**
