### PR TITLE
Add nmark packages.json

### PR DESCRIPTION
**Pull request by kyoheiu**
Hi,
I think not only just `nimble publish` this PR is also needed to be registered to nimble.directory. So, here is PR. Thank you for this great ecosystem.

### CODE REVIEW

**Comment by xflywind** [comment]
Hi @kyoheiu, what's wrong with this PR https://github.com/nim-lang/packages/pull/1886/files?

You can edit your previous PR directly. The previous PR is enough. `nimble.directory` will check them automatically.

**Comment by xflywind** [comment]
Well, I will merge this one.

**Comment by kyoheiu** [comment]
Oh, so second PR wasn't necessary... Sorry, I close this PR.

**Comment by kyoheiu** [comment]
Thank you!

**Comment by xflywind** [comment]
You are welcome

**Pull request closed without merging**
