### PR TITLE
Added package nimzbar

### PR DESCRIPTION
**Pull request by genotrance**

### CODE REVIEW

**Comment by dom96** [comment]
Wow. Nimble crashes with no error when installing this package.

**Comment by genotrance** [comment]
I'll bet you are testing on Mac which I couldn't get working since there is no makefile I could refer to. I've put in an exit on Mac with a message and updated Readme but nimble doesn't print anything. It does work on other OS though.

**Comment by dom96** [comment]
> https://irclogs.nim-lang.org/15-11-2018.html#00:38:41

I'm not going to add this package. Quitting with no message is terrible during an install.

**Comment by genotrance** [comment]
Looks like I missed an echo - I had one in nimFastText. I've pushed a fix with a message.

https://github.com/genotrance/nimzbar/blob/master/nimzbar.nimble#L19

However, even with an echo, nimble doesn't print anything, but quits for sure.

**Comment by dom96** [comment]
Thanks!

**Pull request merged**
