### PR TITLE
Update packages.json

### PR DESCRIPTION
**Pull request by khchen**
Nim's Windows GUI Framework.

### CODE REVIEW

**Comment by dom96** [comment]
```
   Warning: Package 'wnim' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'wnim', but file 'wColors.nim' is in a directory named 'wNim/private/consts' instead. This will be an error in the future.
      Hint: If 'wNim/private/consts' contains source files for building 'wnim', rename it to 'wnim'. Otherwise, prevent its installation by adding `skipDirs = @["wNim/private/consts"]` to the .nimble file.
```

**Comment by khchen** [comment]
I can install locally without warning?

nimble install
Verifying dependencies for wNim@0.1.2
  Info: Dependency on winim@>= 2.4.2 already satisfied
Verifying dependencies for winim@2.4.3
  Info: Dependency on kiwi@>= 0.1.0 already satisfied
Warning: Package 'kiwi' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'kiwi', but file 'common.nim' is in a directory named 'tests' instead. This will be an error in the future.
  Hint: If 'tests' contains source files for building 'kiwi', rename it to 'kiwi'. Otherwise, prevent its installation by adding `skipDirs = @["tests"]` to the .nimble file.
Verifying dependencies for kiwi@0.1.0
Installing wNim@0.1.2
Success: wNim installed successfully.

And this project already have single directory hierarchy for source files, named 'wnim'.
What is the problem?

**Comment by dom96** [comment]
Huh, strange. It seems like there is some regression in latest Nimble that's causing this warning. I'll look into it.

**Comment by khchen** [comment]
Maybe it is the problem about letter case? 
Path should be case insensitive in Windows but nimble don't recognize it.

**Pull request merged**
