### PR TITLE
Beanstalkd

### PR DESCRIPTION
**Pull request by tormaroe**
Would love to have beastalkd.nim included in the nimble index. If you want to provide any feedback on the module as well (I'm learning the language), that would be a great bonus :)

Btw, I tried running `nible build` in my root, but nothing happened. I can find no documentation on this, so I basically haven't verified the .nimble file. Should be ok though.

### CODE REVIEW

**Comment by dom96** [comment]
You shouldn't specify the SSH git url as I think it will only work for people who have write access to your repo.

**Comment by dom96** [comment]
Nothing happened when you executed ``nimble build`` because your nimble file doesn't specify any modules that need to be built. You do so by writing ``bin = "file"``

**Comment by tormaroe** [comment]
Git url fixed in new commit. I thought `nimble build` was some way to verify the package spec, but I realize I was wrong. Thank you.

**Comment by dom96** [comment]
If you want to verify it then run ``nimble install`` :)

**Comment by tormaroe** [comment]
Ahhhh :) Tried it, seems to have installed it properly. Thanks again

**Comment by dom96** [comment]
np :)

**Pull request merged**
