### PR TITLE
remove stripekit

### PR DESCRIPTION
**Pull request by vfehring**
Remove stripekit as it was not meant to be published yet.

### CODE REVIEW

**Comment by Yepoleb** [comment]
Do you want to make this public again soon? Leaving the entry in causes less trouble than re-adding it in a few days.

**Comment by vfehring** [comment]
Yeah, I would be looking to re add it again, but I’m not sure how long it will be. If leaving the entry in is beneficial, then we can do that, and I’ll just squash the repo at this time so there isn’t anything there to download I guess

**Comment by Yepoleb** [comment]
It's simply less maintaining effort. I'd recommend just adding a note to the Readme that says your project is not finished. Anyone who still downloads it is on their own.

**Comment by vfehring** [comment]
Fair enough. We can close this then.

**Pull request closed without merging**
