### PR TITLE
Add fractions library

### PR DESCRIPTION
**Pull request by adelq**

### CODE REVIEW

**Comment by def-** [comment]
Looks like we had the same idea at the same time: https://github.com/Araq/Nim/pull/1840

**Comment by adelq** [comment]
I guess I should've been more persistent :) Araq/Nim#1825. Do you want me to merge this into your pull request?

**Comment by def-** [comment]
I don't know if the pull request will even be accepted.

**Comment by dom96** [comment]
Still want me to merge this? If so, merge with origin/master please.

**Comment by adelq** [comment]
Let's wait until Araq/Nim#1840 gets resolved - if it gets merged into Nim, then I don't see any reason to keep this package and we can close the pull request, but if it gets rejected then it should be merged in.

**Comment by adelq** [comment]
Araq/Nim#1840 was merged, so this package is irrelevant.

**Pull request closed without merging**
