### PR TITLE
Remove Inumon

### PR DESCRIPTION
**Pull request by dizzyliam**
I was overly optimistic about how motivated I would be to maintain this.

### CODE REVIEW

**Comment by narimiran** [comment]
We usually don't remove packages once added.

**Comment by dizzyliam** [comment]
I can understand why you would make that call overall. However, I'm pretty sure Inumon has no users who will have their projects suddenly bricked, seeing as there have since come to be much better alternatives that are actually maintained.

**Comment by Clyybber** [comment]
Maybe we should add an `unmaintained` or `deprecated` in such cases?

**Comment by dizzyliam** [comment]
Actually I have just noticed the mention of the `abandoned` tag in the README. Would it be distinct from those tags?

**Pull request closed without merging**
