### PR TITLE
Adding the gerbil package

### PR DESCRIPTION
**Pull request by jasonprogrammer**

### CODE REVIEW

**Comment by narimiran** [comment]
This package is cursed.... CI is again stuck in some infinite loop, I have no idea what to do about it.

**Comment by jasonprogrammer** [comment]
Is there any way to see the results of the CI? Is it possible for me to run any of the checks manually? It is a hybrid package (binary + library), I'm not sure if that would have anything to do with it.

**Comment by narimiran** [comment]
> Is there any way to see the results of the CI?

There would be a way, **if** CI had finished its job.

> It is a hybrid package (binary + library), I'm not sure if that would have anything to do with it.

I doubt.

----

Now when we're out of reasonable solutions, I would try some desperate moves: try to insert your package at some other place in `packages.json`, and put more tags.

**Comment by narimiran** [comment]
I've opened https://github.com/nim-lang/packages/pull/1523 to see if maybe I'll have more luck.

**Comment by narimiran** [comment]
Wooohooo, `gerbil` is finally merged! :)

**Comment by jasonprogrammer** [comment]
Thank you for doing that!!

**Pull request closed without merging**
