### PR TITLE
Added nimblegui

### PR DESCRIPTION
**Pull request by ThomasTJdev**
A simple GUI front for Nimble.
https://github.com/ThomasTJdev/nim_nimble_gui

Please let me know, if you like to reserve the name nimblegui.

### CODE REVIEW

**Comment by ba0f3** [comment]
frist app built w/ UIBuilder ever :+1:

**Comment by dom96** [comment]
Awesome :)

**Comment by dom96** [comment]
Here is what it looks like on macOS :)

screen shot 2018-08-15 at 21 57 15

**Comment by ThomasTJdev** [comment]
Thank you for the picture dom96! And thanks for UIBuilder ba0f3 ;)

**Comment by ba0f3** [comment]
you are welcome!
 Im working on compile-time builder. when its done, you wont need to carry glade file w/ your binary. 
and the binary will smaller, of course

**Comment by ba0f3** [comment]
finally, it's here: https://github.com/ba0f3/uibuilder.nim/blob/master/tests/test1.nim

**Pull request merged**
