### PR TITLE
Add package spinner

### PR DESCRIPTION
**Pull request by Knaque**

### CODE REVIEW

**Comment by Yardanico** [comment]
Looks nice, just one thing I want to propose - add the "fidget" tag too :P

**Comment by Knaque** [comment]
@Yardanico what would be the easiest way of doing that? Just editing the .json and making another pull request?

**Comment by Yardanico** [comment]
> @Yardanico what would be the easiest way of doing that? Just editing the .json and making another pull request?

Just editing the JSON in this PR? You don't need to create another PR. You can even do that edit on GitHub - go to your packages repo fork, to the branch and edit packages.json there

**Comment by Knaque** [comment]
Done. I didn't even know you could do that.

**Pull request merged**
