### PR TITLE
Renamed packages to follow upcoming nimble package naming conventions.

### PR DESCRIPTION
**Pull request by gmpreussner**

### CODE REVIEW

**Comment by dom96** [comment]
Thanks! But could you instead add new entries for these at the bottom of the file? That way the old names will continue to work for people who have used them already. :)

**Comment by gmpreussner** [comment]
Oh yes, didn't think of that :)

**Comment by gmpreussner** [comment]
Should be fixed now. We might want to add some field for deprecated/obsolete packages, so that they don't show up in new queries.

**Comment by dom96** [comment]
Agreed :)

**Comment by dom96** [comment]
Thank you for fixing!

**Pull request merged**
