### PR TITLE
Add package set_process_name

### PR DESCRIPTION
**Pull request by juancarlospaco**
https://github.com/juancarlospaco/nim-set-process-name#nim-set-process-name

### CODE REVIEW

**Comment by dom96** [comment]
Would you mind merging all of these small little functions into a single package? I'd really prefer our ecosystem not go the way of npm with packages containing single functions (as much as I would love the package count to go up) :)

**Comment by juancarlospaco** [comment]
@dom96 You merge this one and I continue grouping the small ones or you gonna reject this one?.
I ask to plan what to do...

**Comment by dom96** [comment]
If you agree then please make a new PR with a package that describes its purpose. These functions would belong in some sort of operating systems utilities package, maybe name it ``osutils`` or something.

**Comment by juancarlospaco** [comment]
:+1:

**Pull request closed without merging**
