### PR TITLE
Added odbc library

### PR DESCRIPTION
**Pull request by coffeepots**

### CODE REVIEW

**Comment by dom96** [comment]
Your package doesn't conform to Nimble directory structure guidelines. Please fix.

**Comment by coffeepots** [comment]
In process. Taking this as an opportunity to also update the code and add more comprehensive tests, etcetera.

**Comment by dom96** [comment]
Any progress?

**Comment by coffeepots** [comment]
Sorry, this has been on hold as I haven't had time to work on it lately, but I'll be getting back to it soon. If it's preferable I can close this and resubmit when it's done?

**Comment by dom96** [comment]
That's okay. No need to close.

**Comment by dom96** [comment]
Any news?

**Comment by dom96** [comment]
I'm afraid I'm going to close this. Please reopen if you want it in Nimble.

**Pull request closed without merging**
