### PR TITLE
Add bgfxdotnim

### PR DESCRIPTION
**Pull request by zacharycarter**
Add bgfxdotnim (BGFX C99 bindings)

### CODE REVIEW

**Comment by narimiran** [comment]
1. @dom96 how do you feel about removing a package from nimble?

2. @zacharycarter Before merging, I would recommend adding `README.md` to your repository, where you explain what your package does, and how to use it.

**Comment by zacharycarter** [comment]
@narimiran - will add a README this morning.

Regarding the existing BGFX package in nimble's dir - I can certainly amend the PR to keep the existing BGFX bindings from halsyss but since they haven't been updated in over a year and they're not usable with the current version of BGFX, I wonder if there's any point in keeping them in the nimble package repo.

**Comment by Araq** [comment]
@narimiran A Nimble "package repository" where stuff can disappear from nilly-willy is **unusable** IMHO. Nimble needs to fork every registered nimble package and old stuff should live forever. Exception: Packages with terrible security implications.

**Comment by narimiran** [comment]
@Araq I thought that might be the case. Now I closed #944 for the same reason.

@zacharycarter will you modify this PR to only add your package?

**Comment by zacharycarter** [comment]
Will do, thanks!

**Comment by dom96** [comment]
Yes, what @Araq said. Packages **should not** be removed, for any reason. This is one of the reasons why we need our own centralised package repo.

**Comment by zacharycarter** [comment]
@narimiran done!

**Pull request merged**
