### PR TITLE
Added package choosenim

### PR DESCRIPTION
**Pull request by genotrance**
https://github.com/dom96/choosenim/issues/56

### CODE REVIEW

**Comment by timotheecour** [comment]
can it point to the origin https://github.com/dom96/choosenim instead of https://github.com/genotrance/choosenim  ? 
else, maybe rename the pkg to genotrance-choosenim or something?

**Comment by genotrance** [comment]
Glad you caught that! This is for the original package, I used my fork without thinking twice.

**Comment by timotheecour** [comment]
nimble install choosenim

```
...
Verifying dependencies for osinfo@0.3.1
 Installing choosenim@#head
   Building choosenim/choosenim using c backend
       Tip: 50 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: choosenim
        ... Details:
        ... Execution failed with exit code 1

. /Users/timothee/git_clone/nim/Nim/lib/system/fatal.nim(76, 5) `raise e` Error: unhandled exception: /private/var/folders/ll/dtd6ksrn50n3xkdy4y61tf_80000gn/T/nimble_15610/githubcom_dom96choosenim_#head/src/choosenim/switcher.nim(13, 11) `"operation successful" in output` Couldn't compile proxyexe [AssertionError]

...

**Comment by timotheecour** [comment]
after fixing above bug with dom96/choosenim#159 I'm getting this:
```
 ... # Importing /Users/timothee/.cache/nim/nimterop/nimarchive/libarchive/libarchive/archive.h
        ... 1578825654
        ... /Users/timothee/git_clone/nim/choosenim/src/choosenim.nim(9, 1) `import choosenim/[download, builder, switcher, common, cliparams, versions]` template/generic instantiation from here
        ... /Users/timothee/git_clone/nim/choosenim/src/choosenim/download.nim(7, 1) `import cliparams, common, switcher, telemetry, utils` template/generic instantiation from here
        ... /Users/timothee/git_clone/nim/choosenim/src/choosenim/telemetry.nim(13, 1) `import cliparams, common, utils` template/generic instantiation from here
        ... /Users/timothee/git_clone/nim/choosenim/src/choosenim/utils.nim(4, 1) `import nimarchive` template/generic instantiation from here
        ... /Users/timothee/.nimble/pkgs/nimarchive-0.3.4/nimarchive/archive.nim(115, 10) `cImport(archivePath, recurse = true)` Error: expression '1578825654' is of type 'int literal(1578825654)' and has to be discarded

```

**Comment by dom96** [comment]
What is the purpose of this? The only one I can think of is updating choosenim, but choosenim itself can do this via `choosenim update self`, so why else add it to the Nimble package listing?

**Comment by genotrance** [comment]
@timotheecour: can you please verify that you have the latest nimterop and not #head?

@dom96: i'm in sync with your comment in the [issue](https://github.com/dom96/choosenim/issues/56#issuecomment-573421153).

**Comment by zedeus** [comment]
Piping curl through sh is generally frowned upon, and most Linux users probably install Nim via their package managers first. If they want to update to devel, or their distro had an outdated version, it's imo more convenient to `nimble install choosenim` than using the questionable installation method of `curl | sh`, plus you let nimble manage it like a package. This is based on my own experience and what I've seen with people I know and in Nim chats.

**Comment by genotrance** [comment]
Sounds fair. Then the only thing the user needs to do is add `~./nimble/bin` first in their path and they will be able to use the choosenim installed toolchains. Of course, there's no way to select the system version of Nim from that point, though maybe choosenim could add that as a channel.

**Comment by timotheecour** [comment]
> Piping curl through sh is generally frowned upon

same sentiment (cf https://github.com/dom96/choosenim/issues/56#issuecomment-379850427)

**Pull request merged**
