### PR TITLE
Added package iniplus

### PR DESCRIPTION
**Pull request by systemonia**

### CODE REVIEW

**Comment by systemonia** [comment]
Crap, I accidentally modified other packages

**Comment by systemonia** [comment]
ill re-open with a better PR

**Comment by narimiran** [comment]
> Crap, I accidentally modified other packages

That's not why CIs are failing. This is:

> E: iniplus has an unreachable download URL: https://systemoniagit/systemonia/iniplus

**Comment by systemonia** [comment]
Ah... I will fix it in my other PR then, thanks!

**Pull request closed without merging**
