### PR TITLE
Add package nsh

### PR DESCRIPTION
**Pull request by gmshiba**

### CODE REVIEW

**Comment by narimiran** [comment]
I've tried to manually install it before merging, and I got this:

```
Downloading https://github.com/gmshiba/nish using git
sh: apt-get: command not found
sh: yum: command not found
../../../compiler/lineinfos.nim(228) raiseRecoverableError
Error: unhandled exception: unhandled exception: FAILED: yum install tcc [ERecoverableError]
```

**Comment by gmshiba** [comment]
I fixed the bug. I think that I will be fine this time.

**Comment by gmshiba** [comment]
Oh sorry. I got it. I fixed it.

**Comment by genotrance** [comment]
Please resolve conflicts and we can look into merging.

**Comment by narimiran** [comment]
> Please resolve conflicts 

...or just wait and I'll do it for you :smile:

**Pull request merged**
