### PR TITLE
Add package RaytracingAlgorithm

### PR DESCRIPTION
**Pull request by lorycontixd**

### CODE REVIEW

**Comment by lorycontixd** [comment]
@xflywind first time trying to publish a package, am I missing something? don't understand why tests fail.

**Comment by xflywind** [comment]
@lorycontixd Hi, you have submitted three same packages to this repo. I merged the first one. The scanner will check whether a newly added package has the same name as the existing package. The test will fail if it is. If you need to change the description, edit the existing infos please.

**Comment by lorycontixd** [comment]
@xflywind  Ok thank you very much. How do I see the published package on nimble? I tried to search for it using nimble search but could not find it. Sorry for the ignorance.

**Comment by xflywind** [comment]
https://nimble.directory/pkg/raytracingalgorithm

**Comment by narimiran** [comment]
> I tried to search for it using nimble search but could not find it. Sorry for the ignorance.

You probably need to do `nimble update` first.

**Pull request closed without merging**
