### PR TITLE
sandia openshmem PR

### PR DESCRIPTION
**Pull request by ct-clmsn**
this PR adds support for openshmem to nim

### CODE REVIEW

**Comment by xflywind** [comment]
Hello, @ct-clmsn
This PR doesn't seem to contain any commit.

**Comment by ct-clmsn** [comment]
@xflywind apologies - will send fix very soon.

**Comment by xflywind** [comment]
ping

**Comment by PhilippMDoerner** [comment]
It has been almost a year, @ct-clmsn everything alright?

**Comment by ct-clmsn** [comment]
@PhilippMDoerner all is well, what is the block on this PR?

**Comment by ringabout** [comment]
Really? where are your changes?

**Comment by ct-clmsn** [comment]
8 commits, no files changed. I haven't had this issue before. @ringabout could you check the commits tab? It shows which files have been changed and where the files have been changed. I'm not sure what the issue is on my end.

**Comment by ct-clmsn** [comment]
PR closed made OBE (over taken by events) by other PRs

**Pull request closed without merging**
