### PR TITLE
Add package nimhttpd

### PR DESCRIPTION
**Pull request by h3rald**

### CODE REVIEW

**Comment by dom96** [comment]
screen shot 2018-05-05 at 18 33 47

**Comment by h3rald** [comment]
Yes but... I specified that file within **skipFiles** as requested, what would be the best place for a nakefile otherwise?

**Comment by dom96** [comment]
It seems like you can put all of that into your .nimble file (you're still using the old .nimble file format too). In either case, the nakefile shouldn't be installed.

**Comment by h3rald** [comment]
I see! I missed the new format somehow... However, if I do that I cannot import the nimble file in the main file because the modules have the same name (nimhttpd.nim and nimhttpd.nimble), and I need a way to store the program name and above all the version number in a single file.

Would the whole nimble packaging still work if I put the package details (name, version, description, etc.) in another file and then import it from nimhttpd.nimble?

**Comment by h3rald** [comment]
There... version 1.0.5 should be properly "nimble-compliant". Using NimScript for the nimble file made things simpler, BUT now I have to update the version number in two different files (nimhttpd.nimble and nimhttpd.nim). Any idea on how to solve this?

**Comment by dom96** [comment]
> Would the whole nimble packaging still work if I put the package details (name, version, description, etc.) in another file and then import it from nimhttpd.nimble?

Yep

**Comment by dom96** [comment]
Hrm, now your package isn't building for me.

**Comment by h3rald** [comment]
I see... OK, I modified the project structure and tested it with nimble check and nimble build. Everything should be in order now...

**Comment by dom96** [comment]
Thanks :)

**Pull request merged**
