### PR TITLE
Move to working fork of ncurses wrapper

### PR DESCRIPTION
**Pull request by Patasuss**
The [original version](https://github.com/rnowley/nim-ncurses/) has an out of date .nimble file which does not work with the current version of nimble.
See [this issue](https://github.com/rnowley/nim-ncurses/issues/21) in the original repo. Someone made a [PR](https://github.com/rnowley/nim-ncurses/pull/25) with a fix, but the maintainer seems inactive.

I forked the repo, fixed the .nimble file and corrected a compiler error within ncurses.nim.

### CODE REVIEW

**Comment by narimiran** [comment]
> Someone made a PR with a fix, but the maintainer seems inactive.

I'm surprised to see that the changes in that PR are needed, because the existing version seems to follow what is written here: https://github.com/nim-lang/nimble#creating-packages

@genotrance @dom96 any idea why the original package and its .nimble file doesn't work?

**Comment by Patasuss** [comment]
This is the error log I get:

```
madpat nim-ncurses> nimble --version
nimble v0.12.0 compiled at 2020-10-15 07:47:11
git hash: 8f7af860c5ce9634af880a7081c6435e1f2a5148
madpat nim-ncurses> nimble install
     Error: Could not read package info file in /home/madpat/tmp/nim/nim-ncurses/ncurses.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     /home/madpat/tmp/nim/nim-ncurses/ncurses.nimble(2, 1) Error: undeclared identifier: 'name'
        ... printPkgInfo() failed.
```

Also I failed to mention that I fixed a bug in the current ncurses wrapper. The fix is included in the fork I made.

```
madpat nim-ncurses> cd example/
madpat example> nim c helloworld.nim 
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
.....
/home/madpat/tmp/nim/nim-ncurses/ncurses.nim(237, 32) template/generic instantiation of `NCURSES_BITS` from here
/home/madpat/tmp/nim/nim-ncurses/ncurses.nim(84, 16) Error: 18446744073709551615 can't be converted to chtype

```

**Comment by genotrance** [comment]
Nimble files have never supported the `name` field - it has been called `packageName` for at least [5 years](https://github.com/nim-lang/nimble/blame/8f7af860c5ce9634af880a7081c6435e1f2a5148/src/nimblepkg/nimscriptapi.nim#L17) and is not required since it is derived from the name of the nimble file.

**Comment by Patasuss** [comment]
Are there any problems with this PR that I should know of? It's just sitting here, inactive.

**Pull request merged**
