### PR TITLE
Add NimUnits

### PR DESCRIPTION
**Pull request by Udiknedormin**

### CODE REVIEW

**Comment by dom96** [comment]
screen shot 2018-04-15 at 23 16 18

Move your ``private`` folder into the ``units`` folder.

**Comment by dom96** [comment]
Your private directory still needs to be within a ``units`` namespace. Otherwise it could be wrongly accessed via ``import private/...``.

**Comment by Udiknedormin** [comment]
Do you know why it [fails to autoinstall](https://nimble.directory/ci/badges/units/nimdevel/output.html) on nimble, by any chance? It would be nice for it to have its docs on nimble...

**Comment by dom96** [comment]
@FedericoCeratto ^

**Pull request merged**
