### PR TITLE
add ternary-tree

### PR DESCRIPTION
**Pull request by jiyinyiyong**
Refers to https://github.com/Cirru/ternary-tree .

### CODE REVIEW

**Comment by jiyinyiyong** [comment]
```
   Success: cirru_parser installed successfully.
    Reading official package list
   Checking for ternary-tree@>= 0.1.26
 Installing ternary-tree@>= 0.1.26
    Reading official package list
    Prompt: ternary-tree not found in any local packages.json, check internet for updated packages? -> [forced yes]
Downloading Official package list
     Trying https://github.com/nim-lang/packages/raw/master/packages.json
   Warning: Could not download: Invalid argument
     Trying http://irclogs.nim-lang.org/packages.json
    Success Package list downloaded.
    Reading official package list
     Error: Package not found.
```

https://github.com/nim-lang/nimble/blob/b4f29540bc5ff8a64bc6e672bb5deb25b1959690/src/nimblepkg/packageinfo.nim#L201-L208

a bit weird... tried `wget` and that github link worked. `Invalid argument` looks strange.

**Comment by narimiran** [comment]
Maybe it is a temporary GitHub hiccup? Did you try again?

**Comment by jiyinyiyong** [comment]
Tried multiple times, with WiFi and 4G network.. all failed.

**Comment by narimiran** [comment]
Ok, I can reproduce it.

Maybe it is because of `-` in the package name? :/

**Comment by jiyinyiyong** [comment]
I think the error happened during fetching `packages.json` from GitHub, probably GitHub returned that error. I `wget` and put content into my local `~/.nimble/packages_official.json` and it's working correctly now.

**Comment by narimiran** [comment]
Today I was able to install this package successfully. Can you confirm?

**Comment by dom96** [comment]
You shouldn't have dashes in Nimble package names, I see that your repo's .nimble file doesn't have a dash in it either. This package is mis-named.

@narimiran please do not merge packages with dashes in the name

**Comment by narimiran** [comment]
> @narimiran please do not merge packages with dashes in the name

Ok, I'll be more careful in the future. Didn't know about that rule.

**Pull request merged**
