### PR TITLE
Added NHSL and nim-stopwatch

### PR DESCRIPTION
**Pull request by twist-vector**

### CODE REVIEW

**Comment by dom96** [comment]
Add to the bottom please, and you will need to rename the ``nim-stopwatch`` package: no dashes allowed.

**Comment by dom96** [comment]
On another note, what happened to you!? Just realised you are the guy who started work on nits :)

**Comment by twist-vector** [comment]
OK, I'll move them.

Any thoughts for a better name?  I see there's already a "stopwatch"
package so I don't want to collide with it.  Unfortunately it really is a
stopwatch :)

On Sat, Nov 21, 2015 at 8:04 AM, Dominik Picheta <notifications@github.com>
wrote:

> Add to the bottom please, and you will need to rename the nim-stopwatch
> package: no dashes allowed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nim-lang/packages/pull/273#issuecomment-158636651>.
>



-- 
---
Tom Krauss
thomas.krauss@gmail.com
---
Can of worms?  The can is open, the worms are everywhere.

**Comment by twist-vector** [comment]
Man, it has been a crazy few years.  Medical issue with my daughter, two
new jobs, and an electronics startup.  I haven't really had time for much
else.  Hopefully i can spend a bit of time with Nim again.

On Sat, Nov 21, 2015 at 11:38 AM, Tom Krauss <thomas.krauss@gmail.com>
wrote:

> OK, I'll move them.
>
> Any thoughts for a better name?  I see there's already a "stopwatch"
> package so I don't want to collide with it.  Unfortunately it really is a
> stopwatch :)
>
> On Sat, Nov 21, 2015 at 8:04 AM, Dominik Picheta <notifications@github.com
> > wrote:
>
>> Add to the bottom please, and you will need to rename the nim-stopwatch
>> package: no dashes allowed.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nim-lang/packages/pull/273#issuecomment-158636651>.
>>
>
>
>
> --
> ---
> Tom Krauss
> thomas.krauss@gmail.com
> ---
> Can of worms?  The can is open, the worms are everywhere.
>



-- 
---
Tom Krauss
thomas.krauss@gmail.com
---
Can of worms?  The can is open, the worms are everywhere.

**Comment by dom96** [comment]
You could call it ``nimstopwatch``, I'm not good with names unfortunately :)

That sounds rough, I hope she's ok now!

I think you will find that a lot of things have changed since you left. Hopefully for the better!

**Comment by twist-vector** [comment]
OK, I changed the name to nimstopwatch and recommitted.

I've been playing with Nim again trying to get back up to speed.  I really
like it.  I've also been playing with Elixir which is also quite nice, but
for, I think, a different domain.

Hopefully I can contribute something :)


On Sat, Nov 21, 2015 at 11:57 AM, Dominik Picheta <notifications@github.com>
wrote:

> You could call it nimstopwatch, I'm not good with names unfortunately :)
>
> That sounds rough, I hope she's ok now!
>
> I think you will find that a lot of things have changed since you left.
> Hopefully for the better!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nim-lang/packages/pull/273#issuecomment-158662024>.
>



-- 
---
Tom Krauss
thomas.krauss@gmail.com
---
Can of worms?  The can is open, the worms are everywhere.

**Comment by dom96** [comment]
Awesome! Thank you! Please make sure to add a nimble file in the nimstopwatch repo, otherwise people won't be able to install it.

Yes, please do contribute! Things are getting exciting in Nim land and 1.0 is just around the corner :)

**Pull request merged**
