### PR TITLE
Added shaname.

### PR DESCRIPTION
**Pull request by Torro**
Please add shaname to packages.json.

### CODE REVIEW

**Comment by Torro** [comment]
@dom96 Perhaps your nim.cfg is missing the path to the sha1 library? or do I need to add Nim standard libraries as dependencies to the .nimble? Please let me know how to proceed.

In Gentoo I had to append `path="$lib/std"` manually to nim.cfg; cooking up a bug and a patch for this as we speak.

**Comment by dom96** [comment]
Ahh.  `import shame/sha1`

On 16 May 2018 08:55, "Torro" <notifications@github.com> wrote:

@dom96 <https://github.com/dom96> Perhaps your nim.cfg is missing the path
to the sha1 library? or do I need to add Nim standard libraries as
dependencies to the .nimble? Please let me know how to proceed.

In Gentoo I had to append path="$lib/std" manually to nim.cfg; cooking up a
bug and a patch for this as we speak.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nim-lang/packages/pull/739#issuecomment-389429210>, or mute
the thread

**Comment by Torro** [comment]
@dom96 come again?

**Comment by dom96** [comment]
*std/sha1

Sorry. I'm writing on my phone. That module is inside the `std` package.
IMO it should be importable without that prefix, but that's a bug report
for another time.

**Comment by Torro** [comment]
No problem. Should be fixed now. Thanks :)

**Comment by dom96** [comment]
Brilliant, thanks!

**Comment by Torro** [comment]
@dom96 Sure thing. Happy to contribute :)

**Pull request merged**
