### PR TITLE
Add package gurl

### PR DESCRIPTION
**Pull request by MaxUNof**

### CODE REVIEW

**Comment by narimiran** [comment]
> `"url": "https:///"`

> `"web": "https:///"`

This won't do. We need a link to your code repository.

**Comment by MaxUNof** [comment]
Code repository - https://github.com/MaxUNof/gurl

**Comment by SolitudeSF** [comment]
please, read this https://github.com/nim-lang/nimble#creating-packages

**Comment by narimiran** [comment]
You need to add that to `packages.json`.

Btw, your package doesn't include a `.nimble` file, which is required, and there is no `README.md` which is not "officially required" but I'm not merging any packages without it (where you explain what your package is, what it does, and how to use it).

----

@SolitudeSF has given you the link with the instructions how to create a nimble package. I'm closing this, but feel free to open another PR when you meet the requirements.

**Pull request closed without merging**
