### PR TITLE
Add package result

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by dom96** [comment]
Your package needs a .nimble file.

**Comment by dom96** [comment]
Ping @arnetheduck

**Comment by arnetheduck** [comment]
fixed

**Comment by arnetheduck** [comment]
fixed I think, pushed to the wrong branch.. 
```
[arnetheduck@tempus nim-result]$ nimble install https://github.com/arnetheduck/nim-result
Downloading https://github.com/arnetheduck/nim-result using git
  Verifying dependencies for result@0.1.0
 Installing result@0.1.0
    Prompt: result@0.1.0 already exists. Overwrite? [y/N]
    Answer: y
   Success: result installed successfully.
```

**Pull request merged**
