### PR TITLE
Add validation package

### PR DESCRIPTION
**Pull request by captainbland**
This adds a package for validating Nim object fields using object field pragmas. Tested under 0.18.0. Thanks for your time.

### CODE REVIEW

**Comment by dom96** [comment]
Nice! But please fix these warnings first :)

screen shot 2018-06-12 at 19 41 47

**Comment by captainbland** [comment]
Hi Dom, thanks for updating me on this. I'm working on this over the weekend so I should have the change for you if not today then tomorrow at some point.

**Comment by captainbland** [comment]
Okay, I've fixed that issue now.

**Comment by dom96** [comment]
Awesome, thanks for fixing.

**Pull request merged**
