### PR TITLE
Add package nim_seq

### PR DESCRIPTION
**Pull request by Unaimend**

### CODE REVIEW

**Comment by SolitudeSF** [comment]
why not dna_seq? this is name is half redundant, half misleading.

**Comment by Unaimend** [comment]
So whats wrong with the travis status report?

**Comment by Unaimend** [comment]
It's not my package so I have no idea, but I would agree that its a perfect name, but dna_seq also would not fit since we plan to implement a lot more bioinformatics related file formats which do not have anything todo with dna.
But anyways there was a way to define a different name for the nimble package, and not use the git one, wasnt there?

**Comment by SolitudeSF** [comment]
> But anyways there was a way to define a different name for the nimble package, and not use the git one, wasnt there?

the name of the package is the name of nimble file.

**Comment by Unaimend** [comment]
I will make the changes and make a new pull request

**Pull request closed without merging**
