### PR TITLE
Add package fision

### PR DESCRIPTION
**Pull request by juancarlospaco**

### CODE REVIEW

**Comment by narimiran** [comment]
What does this do exactly?

**Comment by ba0f3** [comment]
I think this is kind of one-click-install all important packages listed in Nim's testament tests, those packages have zero dependencies and all unittests passing

**Comment by genotrance** [comment]
Fission is with two `s` in case that was the intention.

**Comment by juancarlospaco** [comment]
Theres no intention of anything, thats Spanish.

@ba0f3 Already explained.

This is for the offline Nimmer, people with poor connectivity, that may only have few minutes of internet in a while,
people that only get good internet at school or work, people in rural areas, people stuck offline on a plane,
people on certain countries where other popular programming languages are intentionally blocked to download,
people with no free time to keep up with the latest new package, or if you just want to get important packages because you can.

**Comment by juancarlospaco** [comment]
Feel free to PR Documentation or whatever.
If you want push to any of my packages just tell me, I give ya write access.

**Comment by juancarlospaco** [comment]
ReSync'd, let me know any comments.

**Pull request merged**
