### PR TITLE
Add package glfw

### PR DESCRIPTION
**Pull request by CodeDoes**

### CODE REVIEW

**Comment by dom96** [comment]
This package's nimble file needs to be renamed: https://github.com/ephja/nim-glfw/blob/master/nim_glfw.nimble

Is there a reason @ephja isn't submitting it?

**Comment by CodeVance** [comment]
Yes. @ephja hasn't been on github for a while. I've also tried making a PR
with his repo, but as of yet have not recieved any reply.

**Comment by ephja** [comment]
Isn't the package already in there? Anyway, the format seems to be correct now

**Comment by dom96** [comment]
Yes, this package is already there, but with a wrong name: ``nim-glfw``. Can either of you make a PR to rename it? 

https://github.com/nim-lang/packages#renaming-packages

**Comment by ephja** [comment]
@CodeDoes I see that you previously tried to publish the package, but it was already present in the database, so that's why it didn't work. So all that remains is renaming the package; done in #773

**Comment by CodeDoes** [comment]
Should I close this?

**Pull request closed without merging**
