### PR TITLE
Add package snake

### PR DESCRIPTION
**Pull request by tbutton2005**

### CODE REVIEW

**Comment by narimiran** [comment]
The tests return `E: snake has an unknown method:`. You should put there: `"method": "git"`. And also change `"web": "https:///"`: you can put the same url as in the `url` field above it.

**Comment by dom96** [comment]
https://github.com/dom96/snake. Maybe could rename as well? :)

**Comment by tbutton2005** [comment]
https://github.com/tbutton2005/nim-snake-sfml

**Comment by xflywind** [comment]
Please open a new PR with a unique name.

**Pull request closed without merging**
