### PR TITLE
Add package fsmonitor

### PR DESCRIPTION
**Pull request by thisago**

### CODE REVIEW

**Review by dom96 — CHANGES_REQUESTED** [review]
You'll need to pick a different name, this package already exists: https://github.com/nim-lang/graveyard/tree/master/fsmonitor

**Comment by dom96** [comment]
(Btw the way you're doing fs monitoring from what I can see is really inefficient, consider reimplementing https://github.com/nim-lang/graveyard/tree/master/fsmonitor for async/await)

**Comment by hamidb80** [comment]
looks like mine :D 
https://github.com/hamidb80/watch_for_files

**Comment by thisago** [comment]
@dom96 Thanks for suggestion, I didn't know about the lib `inotify`.

Ok, i will close this for now.

**Pull request closed without merging**
