### PR TITLE
Adding "cucumber_nim"

### PR DESCRIPTION
**Pull request by shaunc**
As a "learning nim" project I've created a port of the cucumber testing framework into nim. As this is my first project, I'm sure it could use a good deal of cleanup. It does run its own tests, at least.

### CODE REVIEW

**Comment by dom96** [comment]
Nice, you will need to rename https://github.com/shaunc/cucumber_nim/blob/master/cucumber_nim.nimble to ``cucumber.nimble`` though.

**Comment by shaunc** [comment]
ah ... and rename cucumber/ to cucumber.pkg/ I guess...?

**Comment by shaunc** [comment]
hmm... using "cucumber.pkg" doesn't seem to work:

    Error: cannot open 'cucumber/types'

I guess "cucumber.nim" isn't a main program... just a convenience module for imports

**Comment by dom96** [comment]
Nope. It should be named ``cucumber/``.

**Pull request merged**
