### PR TITLE
unpublish nimcalcal, calendar

### PR DESCRIPTION
**Pull request by skilchen**
my packages are outdated and unmaintained.

### CODE REVIEW

**Comment by dom96** [comment]
I would prefer if you state in your repo that your package is unmantained. Let others use them if they wish.

**Comment by Araq** [comment]
Well once published, others may depend on it. Nimble needs to fork all packages or we need some other mechanism.

**Comment by skilchen** [comment]
The packages are no longer usable and I won't fix them. So let them disappear from the published package list.

**Comment by dom96** [comment]
It's better to give people something to fix than to make the package disappear completely.

**Comment by skilchen** [comment]
One advantage of unpublishing: the names of the retired packages can be used to publish better alternatives.

Your concerns about disappearing packages are valid. 

But for my packages: 
- i now think it was a mistake to publish them
- it really doesn't matter if they are no longer visible in nimbles package list

So please merge my PR.

**Pull request merged**
