### PR TITLE
Add package spriterot

### PR DESCRIPTION
**Pull request by samdze**
Command line utility to create spritesheets of rotated sprites.

https://github.com/samdze/spriterot

### CODE REVIEW

**Comment by Yepoleb** [comment]
Why is this a draft? If you want this package to be added please mark the pull request ready for review.

**Comment by ringabout** [comment]
It seems fine to merge though.

**Comment by samdze** [comment]
It's a draft because I'm not sure yet regarding the package name.
I'm planning to add a few features that would make the name "spriterot" no longer adequate.

**Comment by ringabout** [comment]
Feel free to open a new PR when it's ready.

**Pull request closed without merging**
