### PR TITLE
Update gnuplot package location

### PR DESCRIPTION
**Pull request by konqoro**

### CODE REVIEW

**Comment by dom96** [comment]
Is @dvolk not interested in maintaining this package anymore?

**Comment by konqoro** [comment]
Yes I asked https://github.com/dvolk/gnuplot.nim/issues/8 As explained, I am going to maintain this package from now on.

**Comment by dom96** [comment]
Your question could be misunderstood, but okay. We can always change it back if @dvolk disagrees.

**Comment by konqoro** [comment]
Yeah but changing it back would also revert the contributions I made, wouldn't it?

**Comment by konqoro** [comment]
Yeah, lol whatever

**Pull request merged**
