### PR TITLE
Add package NimTacToe

### PR DESCRIPTION
**Pull request by JesterOrNot**

### CODE REVIEW

**Comment by narimiran** [comment]
A `readme.md` would be nice to have, where you explain what your package is and how to use it.

Also, filling the `tags` field might help with the discoverability of your package.I would write there at least `tic tac toe` and `game`

**Comment by dom96** [comment]
> `tic tac toe`

`tic-tac-toe` would be better, best for tags not to have spaces.

**Comment by JesterOrNot** [comment]
How does one update a pull request whenever I try to publish again it sends a new PR

**Comment by narimiran** [comment]
> How does one update a pull request whenever I try to publish again it sends a new PR

No problem if you send a new PR (even better since this one now has merge conflict). Once you do, I can close this one.

**Comment by JesterOrNot** [comment]
Got it so you want me to add a readme and I recently added tags is there a tag system for nimble

**Pull request closed without merging**
