### PR TITLE
Add nanoid package

### PR DESCRIPTION
**Pull request by icyphox**
This package is [https://github.com/ai/nanoid](nanoid), implemented in Nim.

### CODE REVIEW

**Comment by jiyinyiyong** [comment]
Something wired.... GitHub problem? Is nanoid still well maintained or should I choose another library?

https://github.com/Cirru/calcit-runner.nim/runs/1498458836?check_suite_focus=true

```
 Installing nanoid@any version
    Reading official package list
Downloading https://github.com/icyphox/nanoid.nim using git
download.nim(93)         getTagsListRemote
Error: unhandled exception: Unable to query remote tags for https://github.com/icyphox/nanoid.nim. Git returned: error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing
 [OSError]
Error: Process completed with exit code 1.
```

**Comment by icyphox** [comment]
Jon <notifications@github.com> wrote:

> Something weird.... GitHub problem? Is nanoid still well maintained or should I choose another library?

Looks like an issue with GitHub, works fine here. As for nanoid being
maintained -- the JS version hasn't changed all that much (aside from
the API); the algorithm in use remains the same. The only thing missing
is async, which I'll probably implement over the weekend.


--
Anirudh Oppiliappan
https://icyphox.sh

**Comment by jiyinyiyong** [comment]
that's quite quick response :D

the thing made me worried was nimble shew me warnings about nanoid. could you look into that as well:

```
 Installing nanoid@any version
Downloading https://github.com/icyphox/nanoid.nim using git
   Warning: Package 'nanoid' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'nanoid', but file 'nonsecure.nim' is in a directory named 'nanoidpkg' instead. This will be an error in the future.
      Hint: If 'nanoidpkg' contains source files for building 'nanoid', rename it to 'nanoid'. Otherwise, prevent its installation by adding `skipDirs = @["nanoidpkg"]` to the .nimble file.
```

**Comment by icyphox** [comment]
Jon <notifications@github.com> wrote:

> that's quite quick response :D
> 
> the thing made me worried was nimble shew me warnings about nanoid. could you look into that as well:

Sure, this package needs some TLC. Will fix. Thanks.
> 
> ```
>  Installing nanoid@any version
> Downloading https://github.com/icyphox/nanoid.nim using git
>    Warning: Package 'nanoid' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'nanoid', but file 'nonsecure.nim' is in a directory named 'nanoidpkg' instead. This will be an error in the future.
>       Hint: If 'nanoidpkg' contains source files for building 'nanoid', rename it to 'nanoid'. Otherwise, prevent its installation by adding `skipDirs = @["nanoidpkg"]` to the .nimble file.
> ```
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nim-lang/packages/pull/875#issuecomment-738746417

--
Anirudh Oppiliappan
https://icyphox.sh

**Pull request merged**
