### PR TITLE
Add package biblioteca_guarrilla

### PR DESCRIPTION
**Pull request by juancarlospaco**
https://github.com/juancarlospaco/biblioteca-guarrilla#biblioteca-guarrilla

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Oh no, you are right, I will check it later, thanks. :disappointed:

**Comment by juancarlospaco** [comment]
It should work now. :slightly_smiling_face:

**Comment by juancarlospaco** [comment]
Version Bump. Sync with Master.

**Comment by narimiran** [comment]
Still the same message.

I guess you also need to bump the git tag/version, not only in the .nimble file.

**Comment by juancarlospaco** [comment]
Bump'd Git Tag `0.1.9`.

**Comment by narimiran** [comment]
Now it installs it successfully, but with some post-install quirks regarding the missing `static` directory. 

I'm merging it, but if you like to solve it @juancarlospaco here is what happens:

```
   Success: biblioteca_guarrilla installed successfully.
    Prompt: Missing file /home/miran/.nimble/pkgs/biblioteca_guarrilla-0.1.9/src/static/css/spectre.min.css. Continue? [y/N]
    Answer: y
    Prompt: Missing file /home/miran/.nimble/pkgs/biblioteca_guarrilla-0.1.9/src/static/css/spectre-exp.min.css. Continue? [y/N]
    Answer: y
    Prompt: Missing directory /home/miran/.nimble/pkgs/biblioteca_guarrilla-0.1.9/src/static. Continue? [y/N]
    Answer: y
    Prompt: Missing directory /home/miran/.nimble/pkgs/biblioteca_guarrilla-0.1.9/src/static/css. Continue? [y/N]
    Answer: y
```

**Comment by juancarlospaco** [comment]
Thanks for the patience :grey_exclamation: 
That is already documented on the readme of the project. Maybe on the future I can just `staticRead` it.

**Pull request merged**
